# Generated by Django 5.1.7 on 2025-06-19 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=100, verbose_name='Марка и модель автомобиля')),
                ('service_date', models.DateField(verbose_name='Предпочтительная дата')),
                ('service_type', models.CharField(choices=[('maintenance', 'Техническое обслуживание'), ('diagnostics', 'Диагностика'), ('engine_repair', 'Ремонт двигателя'), ('transmission_repair', 'Ремонт трансмиссии'), ('suspension_repair', 'Ремонт подвески'), ('brake_repair', 'Ремонт тормозной системы'), ('electrical_repair', 'Ремонт электрики'), ('other', 'Другое')], max_length=50, verbose_name='Тип обслуживания')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_app_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на сервис',
                'verbose_name_plural': 'Заявки на сервис',
                'ordering': ['-created_at'],
            },
        ),
    ]
